### ISSUE TITLE
80 instead of 443

### ISSUE THREAD

**Issue by ramonck** [florianholzapfel/node-kayako#3]
Srs.,

I currently have kayako on port 80 but the api wants to connect to the secure port 443. I don´t have that yet available in my current environment, I tried setting the variable secure and didn´t work.

In order to meet my requirements I changed the protocol line in order to arrange this:
In the client.js
`var protocol = 'http';
	if(config.secure){
	 protocol = config.secure;
	}`

**Comment by florianholzapfel** [comment]
it should already work if you set the ```secure``` config option to ```false```:

```
var client = new kayako({
    host: <kayako-host>,
    apikey: <kayako-apikey>,
    secret: <kayako-secret>,
    secure: false
});
```
