### ISSUE TITLE
Created a Ticket add-on

### ISSUE THREAD

**Issue by ramonck** [florianholzapfel/node-kayako#4]
Florian,

I created a ticket add-on, do you want this code? Can I send it to you?

Best Regards,

**Comment by florianholzapfel** [comment]
Hi,
you are welcome to open a pull request. I will merge the code then. Thank you.

Best regards

**Comment by florianholzapfel** [comment]
that's absolutely ok. you can use ```git rebase -i``` to squash multiple commits into one single commit.

**Comment by florianholzapfel** [comment]
thank you for your work!
