### ISSUE TITLE
Conection issue getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by ruslanguns** [florianholzapfel/node-kayako#7]
I tried to run your code but getting the following error: 

![alt text](https://lh4.googleusercontent.com/8r1M1kQKavXqSFGFGKqIhmvBcwCgUZ5if5Ej7Myvs6DfEug27otD8HAP3jeCzmKCJA9V9GVYHR6UlUL52aVy=w3110-h1666 "getaddrinfo ENOTFOUND")

I am wondering if this is related the HTTPS or a module behind Kayako.

By the way I am using the versión 4.68 of the Kayako Classic and the API is enabled properly.

Thanks in advance.

**Comment by florianholzapfel** [comment]
Hi, i have not worked on this code for years. I also don't have any possibility anymore to test that code.

**Comment by ruslanguns** [comment]
It's okay... Thanks for responding.

**Comment by ruslanguns** [comment]
#
